### ISSUE TITLE
Авторизация по логину и паролю

### ISSUE THREAD

**Issue by SegaWeb** [15web/loymax-php#17]
Есть ли возможность выполнить авторизацию по логину и паролю используя этот SDK? Если нет, то планируется ли добавление такой логики? Спасибо!

**Comment by psprokofiev** [comment]
Да, пример есть в readme  
https://github.com/15web/loymax-php?tab=readme-ov-file#стандартная-аутентификация-требующая-введения-логина-и-пароля

**Comment by pchelk1n** [comment]
Если у вас какие-то проблемы, скиньте сюда описание более развернуто.

**Comment by SegaWeb** [comment]
Нет, проблем нет, авторизоваться получилось.

Но есть еще такой момент...

Мне нужно авторизоваться используя 
'grant_type' => 'client_credentials'

Для использования АПИ без участия самого пользователя (вот как тут описано в документации https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/Authorization_Service/OAuth_authorization/)

Такое возможно?

**Comment by psprokofiev** [comment]
К сожалению, в данной версии не реализована OAuth-авторизация.
Подскажите кейс, в котором возникла необходимость подключить именно ее? Возможно мы сможем помочь.

**Comment by SegaWeb** [comment]
> Подскажите кейс, в котором возникла необходимость подключить именно ее?

Пока конкретного кейса нет, на будущее, для например какой-нибудь массовой обработки пользователей и т.п.

**Comment by psprokofiev** [comment]
Для массовой обработки пользователей лучше использовать Методы системного API.

> Методы API позволяют выполнять различные операции с учетными записями и бонусными счетами Участников ПЛ.
> https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/System_Api_Methods/Methods_of_system_api/

Методы публичного API предназначены для использования по инициативе самого клиента Программы лояльности.

**Comment by psprokofiev** [comment]
@SegaWeb подскажите, нужна ли еще какая-либо помощь по авторизации/регистрации?
