### ISSUE TITLE
Пример регистрации нового пользователя

### ISSUE THREAD

**Issue by SegaWeb** [15web/loymax-php#18]
Покажите, пожалуйста, пример кода SDK для регистрации нового пользователя, используя методы BeginRegistration, RegistrationActions и т.п.

Как должна выглядеть цепочка этих вызовов, используя данный SDK?

Спасибо!

**Comment by psprokofiev** [comment]
В документации есть хороший пример регистрации клиента в Программе лояльности  
https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/API_methods/Papi_examples/Customer_registration/Registration/

В SDK есть методы, необходимые для полного цикла регистрации.  
За исключение пожалуй `/v1.2/User/Questions` - но на практике в нем нет необходимости, поскольку анкета настраивается всегда индивидуально в каждом проекте, и разработчик знает какие вопросы в анкете.  

Также в текущей версии не реализованы методы выпуска или привязки карты, поскольку чаще всего виртуальная карта выпускается при регистрации автоматически (это настраивается в Личном кабинете Лоймакс).

**Comment by SegaWeb** [comment]
Понял, спасибо!
